### ISSUE TITLE
Indexer crash after Fix/improvements (#52)

### ISSUE THREAD

**Issue by gruberx** [Zondax/namadexer#59]
After this: https://github.com/Zondax/namadexer/issues/56 When indexing Namada public-testnet-14.5d79b6958580 again at the block 26314, the indexer crashes with the following error:

The last lines of the log:
```
thread 'main' panicked at /usr/src/namadexer/src/database.rs:643:78:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The full log file is attached.

The log shows that attributes[0] is key: "initialized_accounts", not key: "code" and its value is not a number. The "attributes" have been rearranged. If you look further, attributes[5] is no longer key: "hash" and there is a rearrangement there too.

Part of the log:
```
  2023-12-04T20:48:34.833285Z  INFO namadexer::indexer: Got block 26314
    at src/indexer/mod.rs:51
    in namadexer::indexer::get_block with block_height: 26314

[src/indexer/mod.rs:120] &r = Response {
    height: block::Height(26314),
    txs_results: Some(
        [
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [
                    Event {
                        kind: "transfer",
                        attributes: [
                            EventAttribute {
                                key: "source",
                                value: "atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc",
                                index: true,
                            },
                            EventAttribute {
                                key: "target",
                                value: "atest1v4ehgw36x9prjdjrxdrrywpsg3p5y3jzx4pnsvf3geqnsdehgdzrsd69xu65vdp4gvm5gvecxddt05",
                                index: true,
                            },
                            EventAttribute {
                                key: "token",
                                value: "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5",
                                index: true,
                            },
                            EventAttribute {
                                key: "amount",
                                value: "1000",
                                index: true,
                            },
                        ],
                    },
                ],
                codespace: "",
            },
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [
                    Event {
                        kind: "transfer",
                        attributes: [
                            EventAttribute {
                                key: "source",
                                value: "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5",
                                index: true,
                            },
                            EventAttribute {
                                key: "target",
                                value: "atest1v4ehgw36x3prjve3xg6nqdz989prsv6pxsunzwf3x3zngv6zxycnq329xazrxvzrxguyvwphn7rgph",
                                index: true,
                            },
                            EventAttribute {
                                key: "token",
                                value: "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5",
                                index: true,
                            },
                            EventAttribute {
                                key: "amount",
                                value: "50",
                                index: true,
                            },
                        ],
                    },
                ],
                codespace: "",
            },
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [
                    Event {
                        kind: "transfer",
                        attributes: [
                            EventAttribute {
                                key: "source",
                                value: "atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc",
                                index: true,
                            },
                            EventAttribute {
                                key: "target",
                                value: "atest1v4ehgw36x9prjdjrxdrrywpsg3p5y3jzx4pnsvf3geqnsdehgdzrsd69xu65vdp4gvm5gvecxddt05",
                                index: true,
                            },
                            EventAttribute {
                                key: "token",
                                value: "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5",
                                index: true,
                            },
                            EventAttribute {
                                key: "amount",
                                value: "1000",
                                index: true,
                            },
                        ],
                    },
                ],
                codespace: "",
            },
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [],
                codespace: "",
            },
        ],
    ),
    finalize_block_events: [],
    begin_block_events: None,
    end_block_events: Some(
        [
            Event {
                kind: "accepted",
                attributes: [
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "9",
                        index: true,
                    },
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 9; Changed keys: #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/30812392B0F00517886F58E84E78E39061C18AA6599A8F1EFC295B15213263C0, #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/3CD046DB365AC36AC62C62031FFD730EB007AC6CC2ABE47236EA4F6A3046C868, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v4ehgw36x3rry32xxepy2se3geqnydzzxqcrxd3sx5crysfcx56rwwfhgeqnjs3cxgunz3fjyzc2c3; VPs result: ",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "30812392B0F00517886F58E84E78E39061C18AA6599A8F1EFC295B15213263C0",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "26314",
                        index: true,
                    },
                ],
            },
            Event {
                kind: "accepted",
                attributes: [
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "40",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "26314",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "FBA104388F59DF855868CBBB2450246237FBCF4F349F88BBEF17CB12A53B596B",
                        index: true,
                    },
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 40; Changed keys: #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/9BB0B086AA88BC193F6E6083C06637FD6F1CB5DC1BB86065987CB4FFC47F2E06, #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/FBA104388F59DF855868CBBB2450246237FBCF4F349F88BBEF17CB12A53B596B, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36xvcrzs2zxfz52vfexycnss6zgepnqdfhxueyvvejxgun2s2yx3q5v3zrgs6yxd2peu36cq, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v4ehgw36x3rry32xxepy2se3geqnydzzxqcrxd3sx5crysfcx56rwwfhgeqnjs3cxgunz3fjyzc2c3; VPs result: ",
                        index: true,
                    },
                ],
            },
            Event {
                kind: "applied",
                attributes: [
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 1781; Changed keys: #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v4ehgw36x9prjdjrxdrrywpsg3p5y3jzx4pnsvf3geqnsdehgdzrsd69xu65vdp4gvm5gvecxddt05; VPs result:  Accepted: atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc, atest1v4ehgw36x9prjdjrxdrrywpsg3p5y3jzx4pnsvf3geqnsdehgdzrsd69xu65vdp4gvm5gvecxddt05, atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck;",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "1781",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "26314",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "632832A49DB297311CA383961EFB9AB0650C7820A20BE44E3B22A8235DF34283",
                        index: true,
                    },
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                ],
            },
            Event {
                kind: "applied",
                attributes: [
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 1684; Changed keys: #atest1v4ehgw36geqng3j9gdznxveexymngwzpgvenjwp3gezyvs33xazyvd3nx4rrywzzg9q5gwfntpuwyd/threshold; VPs result:  Accepted: atest1v4ehgw36geqng3j9gdznxveexymngwzpgvenjwp3gezyvs33xazyvd3nx4rrywzzg9q5gwfntpuwyd;",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "ED47DB988C83D37E965EFE3B87379817E4CC6DE3046D256C044B87F0FA57F0BC",
                        index: true,
                    },
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "26314",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "1684",
                        index: true,
                    },
                ],
            },
        ],
    ),
    validator_updates: [],
    consensus_param_updates: None,
    app_hash: AppHash(),
}
```

Perhaps it makes sense to parse by matching key-values? And access the values via key.

Namadexer Fix/improvements (#52) commit: ea6a49bf080a23e52b0f0f66fb17a0c7891f8f7f

[20231204_log.txt](https://github.com/Zondax/namadexer/files/13551389/20231204_log.txt)

**Comment by gruberx** [comment]
Saw that the tables have changed. Completely erased PostgreSQL and tried to re-index testnet 14, same error on block 72 height.
Block data:
```
  2023-12-05T17:54:22.075291Z  INFO namadexer::indexer: Got block 72
    at src/indexer/mod.rs:51
    in namadexer::indexer::get_block with block_height: 72

[src/indexer/mod.rs:120] &r = Response {
    height: block::Height(72),
    txs_results: Some(
        [
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [],
                codespace: "",
            },
            ExecTxResult {
                code: Ok,
                data: b"",
                log: "",
                info: "",
                gas_wanted: 0,
                gas_used: 0,
                events: [
                    Event {
                        kind: "transfer",
                        attributes: [
                            EventAttribute {
                                key: "source",
                                value: "atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc",
                                index: true,
                            },
                            EventAttribute {
                                key: "target",
                                value: "atest1d9khqw36x5mns3jxxcmyyvfjg9z5xdp4xfzrg33cxy65zwfjxvunyde4xcmnys29g9q5xwpce89c4v",
                                index: true,
                            },
                            EventAttribute {
                                key: "token",
                                value: "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5",
                                index: true,
                            },
                            EventAttribute {
                                key: "amount",
                                value: "200",
                                index: true,
                            },
                        ],
                    },
                ],
                codespace: "",
            },
        ],
    ),
    finalize_block_events: [],
    begin_block_events: None,
    end_block_events: Some(
        [
            Event {
                kind: "accepted",
                attributes: [
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 10; Changed keys: #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/676B40DDC425502706A698725725846D39F92780A7E78CD852EE07AE2CA7A1B3, #atest1v9hx7w362fjhqmrp0ys9qun0w3jkxarfdahzqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq04eufp/C00B529C40C6A7BD9ECD88B25C5C9BEA85F137D75FD85CCF73CCE29B31745382, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36gdzrs32zgvmrydekgcmrzvfjgeqnzd34gvenzdjyxq6ng329gfpry3zzxsu5xv3j4cvsxt, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1v4ehgw36x5erxvjrgcm5vvfjgezrzsfsg3pnzd3excunv3f5x3pyyv34g5u5y3fsxs6rzvf3pty4az; VPs result: ",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "10",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "72",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "C00B529C40C6A7BD9ECD88B25C5C9BEA85F137D75FD85CCF73CCE29B31745382",
                        index: true,
                    },
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                ],
            },
            Event {
                kind: "applied",
                attributes: [
                    EventAttribute {
                        key: "initialized_accounts",
                        value: "[]",
                        index: true,
                    },
                    EventAttribute {
                        key: "gas_used",
                        value: "1770",
                        index: true,
                    },
                    EventAttribute {
                        key: "info",
                        value: "Transaction is valid. Gas used: 1770; Changed keys: #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36x5mns3jxxcmyyvfjg9z5xdp4xfzrg33cxy65zwfjxvunyde4xcmnys29g9q5xwpce89c4v, #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc; VPs result:  Accepted: atest1d9khqw36x5mns3jxxcmyyvfjg9z5xdp4xfzrg33cxy65zwfjxvunyde4xcmnys29g9q5xwpce89c4v, atest1d9khqw36xgurgd2zgverqvejgerrxdfcggm5gdjzg5e5vv698y6nwvpcxeznw3f4xc6y2d69aj6jzc, atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck;",
                        index: true,
                    },
                    EventAttribute {
                        key: "log",
                        value: "",
                        index: true,
                    },
                    EventAttribute {
                        key: "code",
                        value: "0",
                        index: true,
                    },
                    EventAttribute {
                        key: "hash",
                        value: "2C39BC2D419D62695AD0937703154D6C29BBB178BDD5EB9F1EDDE4D459C371A5",
                        index: true,
                    },
                    EventAttribute {
                        key: "height",
                        value: "72",
                        index: true,
                    },
                ],
            },
        ],
    ),
    validator_updates: [],
    consensus_param_updates: None,
    app_hash: AppHash(),
}
```

**Comment by rllola** [comment]
Hey!

Indeed we changed the table and while we are still in testnet we don't do migrations.

Alright that's interesting. I have always assumed the order if the events would appear in the same order because they did consistantly. It is an easy fix I just need to properly look up for the `key == code` to parse it.

Sorry for this inconvenient. I will fix it ASAP.

**Comment by gruberx** [comment]
Glad to be of help.
